### ISSUE TITLE
allow root to login instead of having to use user centos

### ISSUE THREAD

**Issue by arrfab** [dmsimard/centos-cloud#5]
I know that the default for the CentOS 7 cloud images is to use the "centos" user and then sudo, and that root is disallowed logins, but we should revert that for the centos-cloud environment : all $projects using CI are relying on the fact that they have to just ssh as root for their tests on the actual bare-metal setup, so we have to be consistent and allow root login in that CI cloud environment too.
Cloud-init permits that through "disable_root: 0"

**Comment by dmsimard** [comment]
I merged a script that creates an image with the expected fixes in it in https://github.com/dmsimard/centos-cloud/commit/7c8261a849a08b27cbc675643f2850ce2bd58659
