### ISSUE TITLE
cpu_flag sse4_2 is exposed by default to the provisioned VM, breaking some tools like curl/nss

### ISSUE THREAD

**Issue by arrfab** [dmsimard/centos-cloud#6]
reference : https://access.redhat.com/articles/2050743 (see strstr and SSE 4.2 comment)
the workaround is easy but has to be discussed : "touch /etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned"
If we don't either do that, or hide that cpu_flag, curl (for example) doesn't work against TLS enabled website

**Comment by dmsimard** [comment]
I merged a script that creates an image with the expected fixes in it in https://github.com/dmsimard/centos-cloud/commit/7c8261a849a08b27cbc675643f2850ce2bd58659
